name: Build & Deploy docs-next to Github Pages

on:
  # Runs only when a pull request targets deploy-to-github-pages
  pull_request:
    branches:
      - deploy-to-github-pages

  # Allows manual run
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run the workflow on'
        required: false
        default: ''

  # Runs only on pushes to deploy-to-github-pages
  push:
    branches:
      - deploy-to-github-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-main:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: artifact-main
    steps:
      - name: Checkout docs-next
        uses: actions/checkout@v4

      - name: Checkout contribution repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/contribution
          path: ClientApp/external-content/contribution

      - name: Checkout SuperOfficeDocs repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/superoffice-docs
          path: ClientApp/external-content/superoffice-docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ClientApp/package-lock.json

      - run: npm ci
        working-directory: ClientApp

      - name: Build Astro excluding API
        working-directory: ClientApp
        env:
          API_ONLY: 'false'
        run: |
          npm run build
          mkdir -p ../dist-out
          cp -r dist/* ../dist-out/

      - name: Upload main artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-main
          path: dist-out

  build-api:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: artifact-api
    steps:
      - name: Checkout docs-next
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout contribution repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/contribution
          path: ClientApp/external-content/contribution

      - name: Checkout SuperOfficeDocs repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/superoffice-docs
          path: ClientApp/external-content/superoffice-docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ClientApp/package-lock.json

      - run: npm ci
        working-directory: ClientApp

      - name: Build Astro API only
        working-directory: ClientApp
        env:
          API_ONLY: 'true'
        run: |
          npm run build
          mkdir -p ../dist-out
          cp -r dist/* ../dist-out/

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-api
          path: dist-out

  deploy:
    needs: [build-main, build-api]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-main
          path: ./artifacts/main

      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-api
          path: ./artifacts/api

      - name: Merge build outputs
        run: |
          mkdir final-dist
          cp -r artifacts/main/* final-dist/
          cp -r artifacts/api/* final-dist/

      - name: Delete original artifacts to save space
        run: rm -rf artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check if the PR originates from source repo
        id: check_pr_source
        run: |
          echo "PR source: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base repo: ${{ github.repository }}"
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ] && [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR is from a forked repo. Skipping deployment."
            echo "skip_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "skip_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Check final-dist size
        run: du -sh final-dist

      - name: Upload GitHub Pages artifact
        if: steps.check_pr_source.outputs.skip_deploy == 'false'
        uses: actions/upload-pages-artifact@v3
        with:
          path: final-dist

      - name: Deploy to GitHub Pages
        if: steps.check_pr_source.outputs.skip_deploy == 'false'
        id: deployment
        uses: actions/deploy-pages@v4
