name: Build and deploy ASP.Net Core app to Azure Web App - docs-next
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 
      

    steps:
      - name: Checkout docs-next
        uses: actions/checkout@v4

      - name: Checkout contribution repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/contribution
          path: ClientApp/external-content/contribution

      - name: Checkout SuperOfficeDocs repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: SuperOfficeDocs/superoffice-docs
          path: ClientApp/external-content/superoffice-docs

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Set up Node.js (for Astro build)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'ClientApp/package-lock.json'

      - name: Publish project (runs npm + copies frontend via MSBuild target)
        working-directory: ./Server
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-artifact
          path: ${{env.DOTNET_ROOT}}/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-artifact
          path: ./publish

      - name: Create deployment ZIP
        run: |
          cd publish
          zip -r ../app.zip .
          cd ..

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D6201BE9CBA4102A67082079FA9D045 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5F979726F2140149EE71D82B31CE225 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3F73E186A6F2462480840A28C77242B0 }}

      - name: Deploy ZIP to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docs-next'
          package: ./app.zip
